apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
    - name: kubia
      image: zjjfly/kubia-unhealthy:1.0
      ports:
        - containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          port: 8080
          path: /
