apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  # 实际应用中不需要指定selector,让k8s从pod模板中提取
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
        author: jjzi
    spec:
      containers:
        - name: kubia
          image: zjjfly/kubia:1.0
          ports:
            - containerPort: 8080
