apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu
spec:
  nodeSelector:
    gpu: "true"
  containers:
    - name: kubia
      image: zjjfly/kubia:1.0
      ports:
        - containerPort: 8080
          protocol: TCP
