apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  ports:
    - name: http
      port: 80
      # targetPort can use named port,it refer to the name in pod spec.containers.ports.name
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: kubia

