apiVersion: v1
kind: Pod
metadata:
  name: kubia-named-ports
  labels:
    app: kubia
spec:
  containers:
    - name: kubia
      image: zjjfly/kubia:1.0
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
