apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  # this field is set to ClientIP when same client ip need to be dispatched to same pod
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
      app: kubia
